if(CMAKE_SYSTEM_NAME STREQUAL "Windows" OR (NOT CMAKE_SYSTEM_NAME AND CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows"))
    set(env_home "$ENV{USERPROFILE}")
else()
    set(env_home "$ENV{HOME}")
endif()
string(REPLACE "\\" "/" HOME "${env_home}")
set(CPPM_ROOT   ${HOME}/.cppm)
set(CPPM_PREFIX ${CPPM_ROOT})
set(CPPM_MODULE ${CPPM_ROOT}/cmake)
set(CPPM_CACHE  ${CPPM_ROOT}/cache)
set(CPPM_PKGS   ${CPPM_ROOT}/cppkg)
set(CPPM_CORE   ${CPPM_PKGS}/cppm-tools-${CPPM_TOOLS_VERSION})
list(APPEND CMAKE_MODULE_PATH "${CPPM_CORE}")
list(APPEND CMAKE_MODULE_PATH "${CPPM_MODULE}")

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/")
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules/")

include(download/tool)
include(cppm/setting)
include(utility/set_cmake_cache)
include(cppm/cppm_project)
include(utility/cppm_print)
include(cppm/cxx_standard)
include(cppm/compiler_option)
include(cppkg/find)
include(cppm/target_define)
include(cppm/target_dependencies)
include(cppm/target_install)
include(cppkg/download)
