function(cppm_print)
    foreach(message ${ARGV})
        if(NOT ${PROJECT_NAME}_NO_MESSAGE)
            message(STATUS "[cppm] ${message}")
        endif()
    endforeach()
endfunction()

function(cppkg_print)
    foreach(message ${ARGV})
        if(NOT ${PROJECT_NAME}_NO_MESSAGE)
            message(STATUS "[cppkg] ${message}")
        endif()
    endforeach()
endfunction()


function(cppm_error_print)
    foreach(message ${ARGV})
        if(NOT ${PROJECT_NAME}_NO_MESSAGE)
            message(STATUS "[cppm-error] ${message}")
        endif()
    endforeach()
    message(FATAL_ERROR "")
endfunction()
