
macro(cppm_compiler_option)
    cmake_parse_arguments(ARG "DEFAULT;NO_DEFAULT" "" "DEBUG;RELEASE" ${ARGN})
    if(${NO_DEFAULT})
        _cppm_compiler_debug_option(NO_DEFAULT)
        _cppm_compiler_release_option(NO_DEFAULT)
    else()
        _cppm_compiler_debug_option(${ARG_DEBUG})
        _cppm_compiler_release_option(${ARG_RELEAGE})
    endif()
endmacro()

macro(_cppm_compiler_debug_option)
    cmake_parse_arguments(ARG "NO_DEFAULT" "CLANG;GCC;MSVC" "" ${ARGN})

    if(${ARG_NO_DEFAULT})
        set(DEF_CLANG "")
        set(DEF_GCC   "")
        set(DEF_MSVC  "")
    else()
        set(DEF_CLANG "-Wall -fPIC -O0")
        set(DEF_GCC   "-Wall -fPIC -O0")
        set(DEF_MSVC  "/MP")
    endif()

    include(utility/set_cmake_cache)
    if(cppm_build_type STREQUAL "debug")
        if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${DEF_CLANG}")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${ARG_CLANG}")
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${DEF_GCC}")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${ARG_GCC}")
        elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${DEF_MSVC}")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${ARG_MSVC}")
        elseif (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${DEF_CLANG}")
            add_compiler_option(CMAKE_CXX_FLAGS_DEBUG "${ARG_CLANG}")
        endif()
        cppm_print("Compiler Option: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_DEBUG}")
    endif()
endmacro()

macro(_cppm_compiler_release_option)
    cmake_parse_arguments(ARG "NO_DEFAULT" "CLANG;GCC;MSVC" "" ${ARGN})
    if(${ARG_NO_DEFAULT})
        set(DEF_CLANG "")
        set(DEF_GCC   "")
        set(DEF_MSVC  "")
    else()
        set(DEF_CLANG "-fPIC")
        set(DEF_GCC   "-fPIC")
        set(DEF_MSVC  "/MP /O2")
    endif()

    include(utility/set_cmake_cache)
    if(cppm_build_type STREQUAL "release")
        if(CMAKE_CXX_COMPILER_ID STREQUAL "Clang")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${DEF_CLANG}")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${ARG_CLANG}")
        elseif(CMAKE_CXX_COMPILER_ID STREQUAL "GNU")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${DEF_GCC}")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${ARG_GCC}")
        elseif (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${DEF_MSVC}")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${ARG_MSVC}")
        elseif (CMAKE_CXX_COMPILER_ID STREQUAL "AppleClang")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${DEF_CLANG}")
            add_compiler_option(CMAKE_CXX_FLAGS_RELEASE "${ARG_CLANG}")
        endif()
        cppm_print("Compiler Option: ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS_RELEASE}")
    endif()
endmacro()
