macro(_cppm_project)
    cmake_parse_arguments(ARG "" "" "" ${ARGN})
    if(${CMAKE_PROJECT_NAME} MATCHES ${PROJECT_NAME})
        set(SUB_PROJECT FALSE)
        set(NO_MESSAGE FALSE)
    else()
        set(SUB_PROJECT TRUE)
        set(NO_MESSAGE TRUE)
    endif()
endmacro()
