macro(cppm_target_dependencies)
    cmake_parse_arguments(ARG "" "" "PRIVATE;PUBLIC;INTERFACE" ${ARGN})
    list(GET ARG_UNPARSED_ARGUMENTS 0 name)
    set(has_deps FALSE)
    if(DEFINED ARG_PUBLIC)
        target_link_libraries(${name} PUBLIC ${ARG_PUBLIC})
        set(has_deps TRUE)
    endif()
    if(DEFINED ARG_PRIVATE)
        target_link_libraries(${name} PRIVATE ${ARG_PRIVATE})
        set(has_deps TRUE)
    endif()
    if(DEFINED ARG_INTERFACE)
        target_link_libraries(${name} INTERFACE ${ARG_INTERFACE})
        set(has_deps TRUE)
    endif()
    if(has_deps)
        message("${ARG_PUBLIC}")
        set(deps)
        string(REPLACE " " "\n-- [cppm]    " pub_dep "${ARG_PRIVATE}")
        string(REPLACE ";" "\n-- [cppm]    " pub_dep "${ARG_PRIVATE}")
        list(APPEND deps "${pub_dep}")
        string(REPLACE " " "\n-- [cppm]    " pri_dep "${ARG_PUBLIC}")
        string(REPLACE ";" "\n-- [cppm]    " pri_dep "${ARG_PUBLIC}")
        list(APPEND deps "${pri_dep}")
        string(REPLACE " " "\n-- [cppm]    " int_dep "${ARG_INTERFACE}")
        string(REPLACE ";" "\n-- [cppm]    " int_dep "${ARG_INTERFACE}")
        list(APPEND deps "${int_dep}")
        string(REPLACE ";" " " deps "${deps}")
        message(STATUS "[cppm] Dependencies:")
        message(STATUS "[cppm]    ${deps}")
    endif()
endmacro()

macro(m_cppm_target_dependencies)
    cmake_parse_arguments(ARG "" "" "PRIVATE;PUBLIC;INTERFACE" ${ARGN})
    list(GET ARG_UNPARSED_ARGUMENTS 0 name)
    set(has_deps FALSE)

    if(DEFINED ARG_PUBLIC)
    foreach(pub IN LISTS ${ARG_PUBLIC})
        target_link_libraries(${name} PUBLIC ${${pub}})
    endforeach()
        set(has_deps TRUE)
    endif()
    if(DEFINED ARG_PRIVATE)
    foreach(pri IN LISTS ${ARG_PRIVATE})
        target_link_libraries(${name} PRIVATE ${${pri}})
    endforeach()
        set(has_deps TRUE)
    endif()
    if(DEFINED ARG_INTERFACE)
    foreach(intf IN LISTS ${ARG_INTERFACE})
        target_link_libraries(${name} INTERFACE ${${intf}})
    endforeach()
        set(has_deps TRUE)
    endif()
    if(has_deps)
        message("${ARG_PUBLIC}")
        set(deps)
        string(REPLACE " " "\n-- [cppm]    " pub_dep "${ARG_PRIVATE}")
        string(REPLACE ";" "\n-- [cppm]    " pub_dep "${ARG_PRIVATE}")
        list(APPEND deps "${pub_dep}")
        string(REPLACE " " "\n-- [cppm]    " pri_dep "${ARG_PUBLIC}")
        string(REPLACE ";" "\n-- [cppm]    " pri_dep "${ARG_PUBLIC}")
        list(APPEND deps "${pri_dep}")
        string(REPLACE " " "\n-- [cppm]    " int_dep "${ARG_INTERFACE}")
        string(REPLACE ";" "\n-- [cppm]    " int_dep "${ARG_INTERFACE}")
        list(APPEND deps "${int_dep}")
        string(REPLACE ";" " " deps "${deps}")
        message(STATUS "[cppm] Dependencies:")
        message(STATUS "[cppm]    ${deps}")
    endif()
endmacro()
